### ISSUE TITLE
启动区块链问题

### ISSUE THREAD

**Issue by YhanJude** [togettoyou/fabric-realty#14]
请问这个咋回事呀
![QQ图片20210723153806](https://user-images.githubusercontent.com/35054695/126751374-6b1b2306-5dbc-48f5-a8f4-e87f55fd7787.png)

**Comment by YhanJude** [comment]
![QQ图片20210723160512](https://user-images.githubusercontent.com/35054695/126754018-3b62f2fd-fd29-481f-a737-00bcc6c4345a.png)
这两个文件没有

**Comment by togettoyou** [comment]
把 docker 镜像的fabric-ccenv（1.4和latest） rmi 删掉，再试试

**Comment by YhanJude** [comment]
不是这个问题

**Comment by YhanJude** [comment]
![image](https://user-images.githubusercontent.com/35054695/127081802-bad0c28b-a821-48eb-aaa4-c74c3e3745a6.png)
这两个文件网上已经没有了

**Comment by togettoyou** [comment]
这个是在容器里面运行的

**Comment by YhanJude** [comment]
Error: error getting endorser client for invoke: endorser client failed to connect to peer0.org1.blockchainrealestate.com:7051: failed to create new connection: context deadline exceeded
最后一步还是报这个错误

**Comment by togettoyou** [comment]
不用看最后一步，你前面的不行 后面自然不行

**Comment by YhanJude** [comment]
一样的操作啊，怎么会出现这个问题

**Comment by togettoyou** [comment]
有试试把 docker 镜像的fabric-ccenv（1.4和latest） rmi 删掉吗

**Comment by YhanJude** [comment]
都删除了，再次运行它又重新下载了

**Comment by togettoyou** [comment]
你前面步骤没报错吧

**Comment by YhanJude** [comment]
![QQ图片20210727095732](https://user-images.githubusercontent.com/35054695/127082983-be56ecc3-3993-4565-98e1-31c09b1ae5fa.png)
![QQ图片20210727095804](https://user-images.githubusercontent.com/35054695/127083001-b2961bb4-0ecf-42de-ae29-25a2e11d63d7.png)
![QQ图片20210727095822](https://user-images.githubusercontent.com/35054695/127083013-5d213777-5345-4a21-b93c-573713857745.png)
![QQ图片20210727095838](https://user-images.githubusercontent.com/35054695/127083024-d0903d7c-9063-4e97-a75c-1c6d0c0efdbc.png)
前面步骤就是这样的

**Comment by togettoyou** [comment]
你的几核几G的

**Comment by togettoyou** [comment]
第七步的时候，有容器被退出了

**Comment by togettoyou** [comment]
你可以先退出docker ps -a 清理掉一些容器先，运行多几次，可能就成功了

**Comment by YhanJude** [comment]
![QQ图片20210727100304](https://user-images.githubusercontent.com/35054695/127083349-97153815-3080-4b2e-a21f-ead2054c1cb1.png)

**Comment by togettoyou** [comment]
那就是网络问题

**Comment by togettoyou** [comment]
运行多几次，会有成功的可能的

**Comment by YhanJude** [comment]
我试试

**Comment by togettoyou** [comment]
要么挂全局梯子

**Comment by YhanJude** [comment]
我在linux上面挂了梯子的

**Comment by togettoyou** [comment]
https://github.com/togettoyou/blockchain-real-estate/issues/10#issuecomment-833364057

**Comment by YhanJude** [comment]
请问我改了一下vue里面的文字，为什么运行的时候还是显示原来的文字呀

**Comment by togettoyou** [comment]
> 请问我改了一下vue里面的文字，为什么运行的时候还是显示原来的文字呀

需要重新编译前端生效 https://github.com/togettoyou/blockchain-real-estate#4%E8%BF%9B%E5%85%A5-vue-%E7%9B%AE%E5%BD%95%E6%89%A7%E8%A1%8C-buildsh-%E7%BC%96%E8%AF%91%E5%89%8D%E7%AB%AF

**Comment by YhanJude** [comment]
请问logo旁边的网址是怎么设计的呀

**Comment by togettoyou** [comment]
> 请问logo旁边的网址是怎么设计的呀

https://github.com/togettoyou/blockchain-real-estate/blob/master/vue/src/layout/components/Sidebar/Logo.vue#L28

**Comment by YhanJude** [comment]
怎么把本地的图标换成logo后面的网址呀

**Comment by togettoyou** [comment]
> 怎么把本地的图标换成logo后面的网址呀

将本地图片放到 /src/assets ，相对路径即可

**Comment by YhanJude** [comment]
![QQ图片20210811101535](https://user-images.githubusercontent.com/35054695/128959456-40d48d97-5e79-4cfe-9e02-dbd636e38761.png)
请问我放在/src/assets下面后，相对路径写的这个，打开页面，显示不出图标

**Comment by togettoyou** [comment]
已修复

**Comment by togettoyou** [comment]
拉取最新代码跑即可

参考：https://jira.hyperledger.org/browse/FAB-13419

**Comment by YhanJude** [comment]
请问我改了vue中的前端代码，重新编译执行，页面没有发生变化怎么回事呀

**Comment by togettoyou** [comment]
> 请问我改了vue中的前端代码，重新编译执行，页面没有发生变化怎么回事呀

可能是 Docker 镜像缓存问题，试试删掉旧的镜像容器

**Comment by YhanJude** [comment]
镜像删完了，重启又重新下载，还是不行呀

**Comment by togettoyou** [comment]
> 镜像删完了，重启又重新下载，还是不行呀

https://github.com/togettoyou/blockchain-real-estate/commit/8737412c2906a11a0584aefd7e3073e108c7a29c

已修复

**Comment by YhanJude** [comment]
Unable to find image 'togettoyou/bockchain-real-estate-vue:v1' locally
请问这个怎么回事呀

**Comment by togettoyou** [comment]
> Unable to find image 'togettoyou/bockchain-real-estate-vue:v1' locally 请问这个怎么回事呀

没事了，参考 https://github.com/togettoyou/blockchain-real-estate/commit/8737412c2906a11a0584aefd7e3073e108c7a29c 已经修复打包不生效的问题了
