### ISSUE TITLE
大佬在启动区块链时报了错，怎么解决啊，求指点

### ISSUE THREAD

**Issue by jieg123456** [togettoyou/fabric-realty#16]
Error: error getting endorser client for invoke: endorser client failed to connect to peer0.org1.blockchainrealestate.com:7051: failed to create new connection: context deadline exceeded

**Comment by togettoyou** [comment]
已修复

**Comment by togettoyou** [comment]
拉取最新代码跑即可

参考：https://jira.hyperledger.org/browse/FAB-13419
