### ISSUE TITLE
数据持久化和docker容器开机自启

### ISSUE THREAD

**Issue by only-someone** [togettoyou/fabric-realty#21]
之前有个版本发现数据没有持久化和开机自启，我部署的虚拟机宕机之后数据全丢了，请问现在解决了吗？能在哪解决？

**Comment by togettoyou** [comment]
数据没有持久化是因为每次执行 start.sh 会默认执行 stop.sh 。

实际上后续重启区块链网络服务只需要执行 `docker-compose restart` 即可


Docker 开机自启参考 https://github.com/togettoyou/fabric-realty/blob/main/Install.md#2-%E9%85%8D%E7%BD%AE-docker-%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF

容器开机自启只需要往 `docker-compose.yaml` 中的服务添加 `restart: always` 参数

**Comment by togettoyou** [comment]
fix
