### ISSUE TITLE
http://localhost:8000/api/v1/queryAccountList出错 偶尔请求成功

### ISSUE THREAD

**Issue by Kele2021** [togettoyou/fabric-realty#25]
data: Transaction processing for endorser [peer0.jd.com:7051]: Chaincode status Code: (500) UNKNOWN. Description: failed to execute transaction 08405a66e161e0b2b76a825d7ebcfd30d4f540a7860162fd3f243c9b5526ec18: error sending: txid: 08405a66e161e0b2b76a825d7ebcfd30d4f540a7860162fd3f243c9b5526ec18(appchannel) exists

**Comment by Kele2021** [comment]
问题查出来了 是由于start.sh中的背书策略指定的是and，但是底下的invoke不是同时发送给and的两个节点背书导致节点vscc验证失败，可以将and改成or，或者同时发送请求

**Comment by togettoyou** [comment]
是的，application 就是同时发送给两个背书节点 
https://github.com/togettoyou/fabric-realty/blob/main/application/server/blockchain/sdk.go#L16
