### ISSUE TITLE
failed to create channel context: failed to get client context to create channel client: user not found[GIN

### ISSUE THREAD

**Issue by Admaing** [togettoyou/fabric-realty#27]
在使用postman发送请求调用，查询账户信息的时候会出现该错误
该错误在blockchain-real的那个版本并没有
![image](https://user-images.githubusercontent.com/38456638/166104306-511f5697-9dfc-4aa6-87e5-a8363dfc34dc.png)
![image](https://user-images.githubusercontent.com/38456638/166104319-c762492d-d2f3-4980-a654-68520e2dd650.png)
直接调用查询用户的链码也不会报错
所以断定问题出现在sdk的配置文件里面，
不过更改配置文件的哪个部分错误都是一样的
所以无法解决错误，请求帮忙

**Comment by togettoyou** [comment]
已更新
