### ISSUE TITLE
Service 'fabric-realty.app' failed to build : Build failed

### ISSUE THREAD

**Issue by BEnser16** [togettoyou/fabric-realty#29]
![image](https://user-images.githubusercontent.com/86014808/181711606-f58163f5-f4d6-4fa2-b662-6d89ea59561b.png)
![image](https://user-images.githubusercontent.com/86014808/181711345-7aa67f40-20e0-4f6b-838a-70714a682911.png)

**Comment by lori-kuo** [comment]
同问

**Comment by togettoyou** [comment]
晚点更新

**Comment by togettoyou** [comment]
fix
