### ISSUE TITLE
部署成功，但是浏览器端http://localhost:8000/web无法访问

### ISSUE THREAD

**Issue by H-L320** [togettoyou/fabric-realty#31]

**Comment by togettoyou** [comment]
看一下最新的readme

**Comment by H-L320** [comment]
![image](https://user-images.githubusercontent.com/72146544/227858723-dcea6fb4-468d-42fe-9f6c-18da251df789.png)

**Comment by H-L320** [comment]
我就是跟着你最新的readme来的

**Comment by togettoyou** [comment]
浏览器访问前端页面 http://localhost:8000/ ，其中后端接口地址为 http://localhost:8888/

**Comment by togettoyou** [comment]
不需要/web 了

**Comment by H-L320** [comment]
![image](https://user-images.githubusercontent.com/72146544/227859215-89cdf491-f89f-47a4-b050-f96664187974.png)

**Comment by togettoyou** [comment]
`docker ps -a` 看一下 `fabric-realty.server` 和 `fabric-realty.web` 是否正常运行

**Comment by H-L320** [comment]
![image](https://user-images.githubusercontent.com/72146544/227859468-0c3c009b-1bc8-4e3f-91d2-42ca078d15ed.png)

**Comment by H-L320** [comment]
![image](https://user-images.githubusercontent.com/72146544/227859785-aef8f8a3-7194-4935-8e2e-0930740f26e9.png)

**Comment by togettoyou** [comment]
我看你是在 Ubuntu 部署的，在 win 访问的，你是不是应该用 Ubuntu 的 IP 访问，而不是 localhost ?

**Comment by H-L320** [comment]
噢噢噢噢

**Comment by H-L320** [comment]
我试一下

**Comment by H-L320** [comment]
解决了，谢谢
