### ISSUE TITLE
区块链浏览器配置问题

### ISSUE THREAD

**Issue by csuboo** [togettoyou/fabric-realty#32]
您好，十分感谢您分享这个项目，它对我帮助很大！我按照您的说明部署了这个项目，但是访问区块链浏览器时发现上面不能正确显示网络的结点数量，在readme展示图片中也是如此。我想问问是不是区块链浏览器的配置问题，如何修正？谢谢！

**Comment by togettoyou** [comment]
可能是的，你可以参考 https://github.com/hyperledger-labs/blockchain-explorer ，如果你可以修复的话，可以提 PR
