### ISSUE TITLE
Can you write another backend version with ExpressJS for this project

### ISSUE THREAD

**Issue by yamaginshi** [togettoyou/fabric-realty#33]
Can you write another backend version with ExpressJS for this project. I tried with ExpressJS for RestAPI but I can't connect to blockchain network.

**Comment by togettoyou** [comment]
I'm sorry, but I'm not familiar with Node.js myself. However, I suggest checking the documentation for ExpressJS and the blockchain network you're trying to connect to. It's possible that there may be some compatibility issues or configuration settings that need to be adjusted. Good luck!
