### ISSUE TITLE
请问这怎么解决？谢谢

### ISSUE THREAD

**Issue by THeartShinesOTMoon** [togettoyou/fabric-realty#35]
我使用curl -sSL https://get.daocloud.io/docker | sh
返回的是sh: 1: cannot open html: No such file
sh: 2: Syntax error: redirection unexpected

**Comment by togettoyou** [comment]
![image](https://github.com/togettoyou/fabric-realty/assets/55381228/78141cea-11d2-4922-9845-ca9d38c99e94)

等官方修复吧

或者其它方式安装就行
