### ISSUE TITLE
err: signature set did not satisfy policy

### ISSUE THREAD

**Issue by phybrain** [togettoyou/fabric-realty#36]
链码初始化成功了，但是报这个错，大佬知道吗

`
validateTx -> ERRO 069 VSCCValidateTx for transaction txId = 50d4ad58d86fed554d1d6ca4bade3b6856a4af5964fe4eede514e6671501fd41 returned error: VSCC error: endorsement policy failure, err: signature set did not satisfy policy
`
![image](https://github.com/togettoyou/fabric-realty/assets/29749341/e15a1a24-ce72-4a04-8727-e2edd08d8d1f)

**Comment by togettoyou** [comment]
看这个看不出来，定位具体哪个步骤出了问题，一般是启动区块链网络的时候，有部分容器启动失败，这个时候再去看失败的容器日志

**Comment by phybrain** [comment]
> 看这个看不出来，定位具体哪个步骤出了问题，一般是启动区块链网络的时候，有部分容器启动失败，这个时候再去看失败的容器日志

启动时所有容器日志都正常，调用链码函数就会报这个错，没头绪
