### ISSUE TITLE
多机搭建方面的求助

### ISSUE THREAD

**Issue by dy-boy** [togettoyou/fabric-realty#37]
你好，如果我想进行多机交互，除了在本机hosts文件配置对应ip和在docker-compose.yaml文件里面修改IP配置信息还需要修改什么吗

**Comment by togettoyou** [comment]
1、保证 `crypto-config` 、`config` 配置，多机都存在各自配置
2、docker-compose拆分到多机，每个节点启动自身的容器，并正确挂载1中的配置
3、application `config.yaml` 等需要连接节点的地方，改成使用 `ip:prot` 连接，或者更改 hosts 配置域名

**Comment by togettoyou** [comment]
其它的得自己看看了，我没试过
