### ISSUE TITLE
localhost:8000启动报错

### ISSUE THREAD

**Issue by ZhaOX732** [togettoyou/fabric-realty#43]
! fabric-realty.web The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested 0.0s          请问大佬启动web跟serve的时候警告这个如何解决

**Comment by togettoyou** [comment]
自己编译下arm64的，或者看能不能开启amd64兼容模式（mac 的话）

**Comment by ZhaOX732** [comment]
> 自己编译下arm64的，或者看能不能开启amd64兼容模式（mac的话）

<img width="1001" alt="image" src="https://github.com/user-attachments/assets/48283ebd-6749-4f32-804b-1e027d87a069">
请问这个serve和web是不是没用启动啊

**Comment by ZhaOX732** [comment]
> 自己编译下arm64的，或者看能不能开启amd64兼容模式（mac的话）

我是pc，怎么编译arm64啊
